spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pokedex}
    username: ${DATABASE_USERNAME:pokedex}
    password: ${DATABASE_PASSWORD:pokedex}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
